spring.application.name=NestedComments

spring.web.error.include-message=always

spring.datasource.url=jdbc:postgresql://localhost:5432/nested_comments
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
